        <link rel="stylesheet" href="assets/css/sections/scss-outputs/general.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/navigator.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/setting.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/count-up.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/scrollbar.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/hero.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/about.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/resume.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/fix-elements.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/skillset.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/duties.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/portfolio.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/overlay-menu.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/preloader.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/testimonial.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/blog.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/contact.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/404-page.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/media.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/dark-scheme.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/flat-style.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/mono.css">
        <link rel="stylesheet" href="assets/css/sections/scss-outputs/mono-flat.css">